Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"

  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "Prometheus"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end
