version: "3.9"

services:
    web:
        container_name: servernode
        build:
            context: .
            dockerfile: .
        environment:
            - PORT=5000
            - MONGODB=mongodb://mongo:27017/kittens
        ports: 
            - "3000:5000"
        volumes:
            - ./:/code
        networks:
            - main
    
    mongo:
        container_name: db
        image: mongo
        ports:
            - 8000:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        networks:
            - main

networks:
    main:

volumes: 
    mongodb:
    mongodb_config: