{
 "title": "Exam dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cpu usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\"} [5m])) by (instance)) / sum(irate(node_cpu_seconds_total[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Ram usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_network_receive_bytes_total[5m])))"
    }
   ]
  },
  {
   "title": "Ram usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes"
    }
   ]
  }
 ]
}