{
 "title": "Prometheus Stats",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\", instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Local Storage Memory Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_local_storage_memory_series{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Internal Storage Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_local_storage_indexing_queue_length{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Target Scrapes (last 5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\",instance=~\"$node\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Samples ingested (rate-5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_ingested_samples_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rule Eval Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "prometheus_evaluator_duration_seconds{quantile!=\"0.01\", quantile!=\"0.05\",instance=~\"$node\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}