Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false
  
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.box="aspyatkin/ubuntu-18.04-server"
      jenkins.vm.hostname = "vm101.do1.exam"
      jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
      jenkins.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
      end
      jenkins.vm.network "private_network", ip: "192.168.56.101"
      jenkins.vm.synced_folder "shared-files/", "/vagrant"
    end

  end
  