/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.helevator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloWorldTest {
    @Test void testSomeLibraryMethod() {
        HelloWorld classUnderTest = new HelloWorld();
    }
}
