global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090

  - job_name: jenkins
    metrics_path: /metrics
    static_configs:
    - targets: [pipelines.do1.exam:9100]

  - job_name: docker
    metrics_path: /metrics
    static_configs:
    - targets: [containers.do1.exam:9100]

  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
    - targets: [monitoring.do1.exam:9100]
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['containers.do1.exam:9999']