Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false
  
    config.vm.define "monitoring" do |monitoring|
      monitoring.vm.box="ubuntu/focal64"
      monitoring.vm.hostname = "vm103.do1.exam"
      monitoring.vm.network "forwarded_port", guest: 3000, host: 8082, auto_correct: true
      monitoring.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.cpus = 4
      end
      monitoring.vm.network "private_network", ip: "192.168.56.103"
      monitoring.vm.provision "shell", path: "scripts/update_hosts.sh"
      monitoring.vm.provision "shell", path: "scripts/install_node3.sh"
      monitoring.vm.synced_folder "shared-files/", "/vagrant"
    end

    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.box="ubuntu/focal64"
      jenkins.vm.hostname = "vm101.do1.exam"
      jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
      jenkins.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.cpus = 4
      end
      jenkins.vm.network "private_network", ip: "192.168.56.101"
      jenkins.vm.provision "shell", path: "scripts/update_hosts.sh"
      jenkins.vm.provision "shell", path: "scripts/install_node1.sh"
      jenkins.vm.synced_folder "shared-files/", "/vagrant"
    end
  
    config.vm.define "docker" do |docker|
      docker.vm.box="ubuntu/focal64"
      docker.vm.hostname = "vm102.do1.exam"
      docker.vm.network "forwarded_port", guest: 8080, host: 8081, auto_correct: true
      docker.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.cpus = 4
      end
      docker.vm.network "private_network", ip: "192.168.56.102"
      docker.vm.provision "shell", path: "scripts/update_hosts.sh"
      docker.vm.provision "shell", path: "scripts/install_node2.sh"
      docker.vm.synced_folder "shared-files/", "/vagrant"
    end

end
  