# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-8"
    docker.vm.hostname = "docker.do2.lab"
    docker.vm.network "private_network", ip: "192.168.99.100"
    docker.vm.provision "shell", inline: <<EOS
echo "* Add EPEL repository ..."
dnf install -y epel-release

echo "* Install Python3 ..." 
dnf install -y python3

echo "* Install Python docker module ..."
pip3 install docker
EOS
    docker.vm.synced_folder "roots/", "/srv/salt"
    docker.vm.provision :salt do |sa|
        sa.masterless = true
        sa.minion_config = "minionfiles/minion.yml"
        sa.run_highstate = true
        sa.verbose = true
    end
  end
end
