/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.helevator;

public class HelloWorld {
    public static void main(String[] args) {
        System.out.println(sayHello("World"));
    }

    public static String sayHello(String name) {
        return "Hello, " + name;
    }
}
