# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-8"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.101"
    web.vm.synced_folder "roots/web/", "/srv/salt"
    web.vm.provision :salt do |sa|
        sa.masterless = true
        sa.minion_config = "minionfiles/minion.yml"
        sa.run_highstate = true
        sa.verbose = true
    end
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/debian-11"
    db.vm.hostname = "db.do2.lab"
    db.vm.network "private_network", ip: "192.168.99.102"
    db.vm.synced_folder "roots/db/", "/srv/salt"
    db.vm.provision :salt do |sa|
        sa.masterless = true
        sa.minion_config = "minionfiles/minion.yml"
        sa.run_highstate = true
        sa.verbose = true
    end
  end
end
