# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false
  
  $puppetrpm = <<PUPPETRPM
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPETRPM

  $puppetdeb = <<PUPPETDEB
    wget https://apt.puppet.com/puppet7-release-focal.deb
    sudo dpkg -i puppet7-release-focal.deb
    sudo apt-get update
    sudo apt-get install -y puppet
PUPPETDEB

  $modulesweb = <<MODULESWEB
    puppet module install puppetlabs-firewall
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESWEB
    
  $modulesdb = <<MODULESDB
    puppet module install puppetlabs/mysql
    sudo cp -vR ~/.puppet/etc/code/modules/ /etc/puppet/code/
MODULESDB

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-8"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.101"
    web.vm.provision "shell", inline: $puppetrpm, privileged: false
    web.vm.provision "shell", inline: $modulesweb, privileged: false
    
    web.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "web.pp"
      puppet.options = "--verbose --debug"
    end
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/debian-11"
    db.vm.hostname = "db.do2.lab"
    db.vm.network "private_network", ip: "192.168.99.102"
    db.vm.provision "shell", inline: $puppetdeb, privileged: false
    db.vm.provision "shell", inline: $modulesdb, privileged: false

    db.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "db.pp"
      puppet.options = "--verbose --debug"
    end
  end
end
