{
 "title": "Exam dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running {{ instance }}" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O {{ instance }}" }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\"} [5m])) by (instance)) / sum(irate(node_cpu_seconds_total[5m])) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ram usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }} {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used {{instance}}"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free {{instance}}" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers {{instance}}" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached {{instance}}" }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }} {{ instance }} "
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  }
 ]
}