# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "jdhost" do |jdhost|
    jdhost.vm.box="ubuntu/trusty64"
    jdhost.vm.hostname = "jdhost.do1.lab"
    jdhost.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
    end
    jdhost.vm.network "private_network", ip: "192.168.56.100"
    jdhost.vm.network "forwarded_port", guest: 8080, host: 8080
    jdhost.vm.provision "shell", path: "install_common.sh"
    jdhost.vm.provision "shell", path: "install_docker.sh"
	  jdhost.vm.provision "shell", path: "install_jenkins.sh"
  end

end
