/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.helevator;

import org.junit.jupiter.api.*;

class HelloWorldTest {
    private HelloWorld helloWorld;

    @BeforeEach
    public void before() throws Exception {
        this.helloWorld = new HelloWorld();
    }

    @AfterEach
    public void after() throws Exception {
        this.helloWorld = null;
    }

    @Test
    void testSayHello() {
        String got = this.helloWorld.sayHello("World");
        String want = "Hello, World";

        Assertions.assertEquals(got, want, "Method should return Hello, World");
    }
}
