# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false
  
    config.vm.define "web" do |web|
      web.vm.box = "shekeriev/debian-11"
      web.vm.hostname = "web.do2.lab"
      web.vm.network "private_network", ip: "192.168.56.100"
      web.vm.network "forwarded_port", guest: 80, host: 8080
    end
    
    config.vm.define "db" do |db|
      db.vm.box = "shekeriev/debian-11"
      db.vm.hostname = "db.do2.lab"
      db.vm.network "private_network", ip: "192.168.56.101"
    end

  end
  