# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-8"
    web.vm.hostname = "web.do2.lab"
    web.vm.network "private_network", ip: "192.168.99.101"
    web.vm.provision "chef_solo" do |chef|
        chef.product = "chef-workstation"
        chef.arguments = "--chef-license accept"
        chef.run_list = [
        "recipe[hwweb::default]"
        ]
    end
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/debian-11"
    db.vm.hostname = "db.do2.lab"
    db.vm.network "private_network", ip: "192.168.99.102"
    db.vm.provision "chef_solo" do |chef|
        chef.product = "chef-workstation"
        chef.arguments = "--chef-license accept"
        chef.run_list = [
        "recipe[hwdb::default]"
        ]
    end
  end
end
